name: Upload Python Package (multiplatform)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheels:
    name: Build ${{ matrix.archs }} ${{ matrix.build }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        archs: ["x86_64, i686", "aarch64", "ppc64le", "s390x"]
        build: ["manylinux", "musllinux"]
        include:
          - os: windows-2019
            archs: "AMD64"
          - os: windows-2019
            archs: "x86"
          - os: macos-11
            archs: "x86_64, arm64"
    env:
      CIBW_ARCHS_LINUX: x86_64 i686 aarch64
      CIBW_ARCHS_MACOS: x86_64 universal2
      CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-*"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_ARCHS: "${{ matrix.archs }}"
          CIBW_BUILD: "${{ matrix.build && '*-' || ''}}${{ matrix.build }}*"
          CIBW_PRERELEASE_PYTHONS: "${{ !startsWith(github.ref, 'refs/tags/v') }}"
      # uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      # with:
      #  user: __token__
      #  password: ${{ secrets.PYPI_API_TOKEN }} 
      #  repository_url: ${{ secrets.PYPI_URL }}
      #  skip_existing: true
      #  path: ./wheelhouse/*.whl
