name: Upload Python Package (multiplatform)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheels:
    name: Build wheel and upload
    # environment: Production 
    environment: Testing 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Build
        run: |
          python -m pip install --upgrade pip build
          python -m build --wheel --outdir ./wheelhouse/ .
      - uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
         user: __token__
         password: ${{ secrets.PYPI_API_TOKEN }} 
         repository_url: ${{ secrets.PYPI_URL }}
         skip_existing: true
         path: ./wheelhouse/*.whl
