# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Test on multiple platforms
on:
  pull_request:
  workflow_call:
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
    - name: Build wheel & install
      shell: bash
      run: |
        python -m build
        ls ./dist/*
        export VALE_VERSION="$(cat pyproject.toml  | grep '^version' | cut -d ' ' -f 3 | sed -e 's/"//g')"
        echo "Installing $VALE_VERSION ..."
        python -m pip install -v "./dist/vale-$VALE_VERSION-py3-none-any.whl"
    - name: Test Vale 
      run: |
        vale --help 
